"""
SMART_AO V7 - __init__.py
================================
Copyright (c) 2026 NOOR - Architecte Principal
Licence: Proprietary - All Rights Reserved
Auteur: NOOR
Date: 06/08/2026
Build: 9 - Phase: 5
"""


"""
SMART_AO V7 - __init__.py
=========================
Source: Arborescence_V7.txt (BIBLE STRUCTURE)
Generated by: bootstrap_v7.py

TODO: Implement according to ARCHITECTURE_V7_ENGINE.md and ENGINEERING-HANDBOOK_V7.md
"""

from .embedding_engine import BGEEmbeddingProvider, get_embedding_provider
from .local_llm import LocalLLMClient, get_local_llm_client
from .confidentialite_detector import ConfidentialiteDetector, detect_confidentialite

__all__ = [
    "BGEEmbeddingProvider",
    "get_embedding_provider",
    "LocalLLMClient",
    "get_local_llm_client",
    "ConfidentialiteDetector",
    "detect_confidentialite",
]

