[alembic]
script_location = app/alembic
prepend_sys_path = .
version_path_separator = os
sqlalchemy.url = postgresql+asyncpg://smart_ao:your_secure_password@localhost:5432/smart_ao_v7

# Additional arguments for the 'version' command
# (the version table is named 'alembic_version' by default)
version_table = alembic_version

# Set this to 'true' to run the environment during
# the 'autogenerate' command
# run_python = true

# Set this to 'true' to run the environment during
# the 'version' command - this requires sqlalchemy.url to be set
# run_python = true

# Set this to 'true' to use the batch mode for autogenerate
# batch_mode = true

# Set this to control how the batch mode separator is used
# batch_separator = 

# Set this to 'true' to use the transaction per migration mode
# transaction_per_migration = true

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers = 
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = 
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
