#!/usr/bin/env bash
# SMART_AO V7 - restore.sh
# Source: Arborescence_V7.txt
# Generated by: bootstrap_v7.py
# FIX-P0: Script de restauration fonctionnel

set -euo pipefail

echo "=========================================="
echo "SMART_AO V7 - Restauration des données"
echo "=========================================="
echo ""

# Variables d'environnement requises
: "${DB_HOST:=localhost}"
: "${DB_PORT:=5432}"
: "${DB_NAME:=smart_ao_v7}"
: "${DB_USER:=smart_ao}"
: "${BACKUP_DIR:=./backups}"

echo "Configuration:"
echo "  DB_HOST: $DB_HOST"
echo "  DB_PORT: $DB_PORT"
echo "  DB_NAME: $DB_NAME"
echo "  DB_USER: $DB_USER"
echo "  BACKUP_DIR: $BACKUP_DIR"
echo ""

# Vérifier que le répertoire de backup existe
if [ ! -d "$BACKUP_DIR" ]; then
    echo "❌ Erreur: Le répertoire de backup n'existe pas: $BACKUP_DIR"
    exit 1
fi

# Trouver le dernier backup disponible
LATEST_BACKUP=$(ls -t "$BACKUP_DIR"/pg_dump_*.sql.gz 2>/dev/null | head -1)

if [ -z "$LATEST_BACKUP" ]; then
    echo "❌ Erreur: Aucun backup trouvé dans $BACKUP_DIR"
    echo "Format attendu: pg_dump_YYYYMMDD_HHMMSS.sql.gz"
    exit 1
fi

echo "✅ Backup trouvé: $LATEST_BACKUP"
echo ""

# Restaurer la base PostgreSQL
echo "→ Décompression et restauration de la base PostgreSQL..."
gunzip -c "$LATEST_BACKUP" | psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME"

if [ $? -eq 0 ]; then
    echo "✅ Base PostgreSQL restaurée avec succès"
else
    echo "❌ Erreur lors de la restauration PostgreSQL"
    exit 1
fi

echo ""
echo "=========================================="
echo "✅ Restauration terminée avec succès"
echo "=========================================="
echo ""
echo "Prochaines étapes recommandées:"
echo "  1. Vérifier les migrations Alembic: alembic upgrade head"
echo "  2. Redémarrer les services: docker-compose restart"
echo "  3. Exécuter un health check: curl http://localhost:8000/health"
echo ""

