#!/bin/bash
# Script de validation de Gate 10 (Revue Finale de Code)
# SMART_AO V7 - Phase 5 Build 9

set -e

echo "=========================================="
echo "Gate 10: Revue Finale de Code"
echo "=========================================="
echo ""

# Répertoire du projet
PROJECT_DIR="/home/noor/PROJECTS/BTP/SMART_AO_V2/SMART_AO_LAST 4/SMART_AO_V7"
cd "$PROJECT_DIR"

# Compteur d'erreurs
errors=0

# =============================================================================
# VALIDATION DE LA REVUE DE CODE
# =============================================================================

echo "Vérification de la revue de code..."
echo ""

# 1. Vérifier que tous les fichiers source ont une licence
echo "→ Vérification des en-têtes de licence..."
license_missing=0
source_files=$(find app -name "*.py" -type f)
for file in $source_files; do
    # Vérifier si le fichier contient un en-tête de licence
    if grep -q "Generated by Mistral Vibe" "$file" || grep -q "SMART_AO V7" "$file" || grep -q "MIT" "$file"; then
        echo "   ✅ $file"
    else
        # Pour les fichiers générés automatiquement, on les ignore
        if grep -q "# AUTO-GENERATED" "$file" || grep -q "# DO NOT EDIT" "$file"; then
            echo "   ⚠️ $file (auto-généré)"
        else
            echo "   ❌ $file - En-tête de licence manquant"
            license_missing=$((license_missing + 1))
        fi
    fi
done

if [ $license_missing -gt 0 ]; then
    echo "   ❌ $license_missing fichier(s) sans en-tête de licence"
    errors=$((errors + license_missing))
fi

# 2. Vérifier l'absence de code mort (TODO, FIXME, XXX)
echo ""
echo "→ Vérification du code mort (TODOs, FIXMEs)..."
todo_count=$(grep -r "# TODO\|# FIXME\|# XXX\|// TODO\|// FIXME\|// XXX" app --include="*.py" --include="*.js" --include="*.ts" 2>/dev/null | wc -l)
if [ $todo_count -eq 0 ]; then
    echo "   ✅ Aucun TODO/FIXME/XXX trouvé"
else
    echo "   ❌ $todo_count TODO/FIXME/XXX trouvés (BLOQUANT pour production)"
    errors=$((errors + todo_count))
fi

# 3. Vérifier la qualité du code avec flake8 (si disponible)
echo ""
echo "→ Vérification de la qualité du code..."
if command -v flake8 &> /dev/null; then
    echo "   Vérification flake8 en cours..."
    if flake8 app --max-line-length=120 --extend-ignore=E203,W503 2>/dev/null; then
        echo "   ✅ flake8: Aucune erreur"
    else
        echo "   ❌ flake8: Des erreurs ont été trouvées (BLOQUANT)"
        errors=$((errors + 1))
    fi
else
    echo "   ⚠️ flake8 non installé - Vérification ignorée"
fi

# 4. Vérifier la complexité cyclomatique (si pylint disponible)
echo ""
echo "→ Vérification de la complexité du code..."
if command -v pylint &> /dev/null; then
    echo "   Vérification pylint en cours..."
    # Ne pas échouer sur les warnings pylint
    pylint app --disable=all --enable=too-many-lines,duplicate-code 2>/dev/null || true
    echo "   ✅ Vérification de complexité terminée"
else
    echo "   ⚠️ pylint non installé - Vérification ignorée"
fi

# =============================================================================
# VALIDATION DE LA DOCUMENTATION TECHNIQUE
# =============================================================================

echo ""
echo "Vérification de la documentation technique..."
echo ""

# Vérifier les fichiers de documentation essentiels
doc_files=(
    "README.md"
    "docs/API_GUIDE_V7.md"
    "docs/USER_GUIDE_V7.md"
    "docs/ARCHITECTURE_DEPLOYMENT_V7.md"
    "docs/DEPLOYMENT_GUIDE_V7.md"
    "k8s/README.md"
)

for file in "${doc_files[@]}"; do
    if [ -f "$file" ]; then
        lines=$(wc -l < "$file")
        echo "   ✅ $file ($lines lignes)"
    else
        echo "   ❌ $file manque"
        errors=$((errors + 1))
    fi
done

# =============================================================================
# VALIDATION DES TESTS
# =============================================================================

echo ""
echo "Vérification de la couverture des tests..."
echo ""

# Vérifier que les tests unitaires existent
test_dirs=(
    "tests/unit"
    "tests/integration"
)

for dir in "${test_dirs[@]}"; do
    if [ -d "$dir" ]; then
        test_count=$(find "$dir" -name "test_*.py" -o -name "*_test.py" | wc -l)
        echo "   ✅ $dir - $test_count fichier(s) de test"
    else
        echo "   ❌ $dir manque"
        errors=$((errors + 1))
    fi
done

# =============================================================================
# VALIDATION DES BONNES PRATIQUES
# =============================================================================

echo ""
echo "Vérification des bonnes pratiques..."
echo ""

# Vérifier l'utilisation des patterns de design
echo "   → Vérification des patterns de design..."
if grep -r "BaseAgent\|AgentRegistry\|WorkflowEngine\|EventBus" app --include="*.py" | grep -v "test" | grep -v ".pyc" > /dev/null 2>&1; then
    echo "   ✅ Patterns de design identifiés"
else
    echo "   ⚠️ Peu ou pas de patterns de design identifiés"
fi

# Vérifier la séparation des préoccupations
echo "   → Vérification de la séparation des couches..."
if [ -d "app/core" ] && [ -d "app/models" ] && [ -d "app/engines" ] && [ -d "app/agents" ]; then
    echo "   ✅ Architecture en couches bien structurée"
else
    echo "   ❌ Architecture en couches incomplète"
    errors=$((errors + 1))
fi

# Vérifier les dépendances
echo "   → Vérification des dépendances..."
if [ -f "requirements.txt" ]; then
    echo "   ✅ requirements.txt existe"
else
    echo "   ❌ requirements.txt manque"
    errors=$((errors + 1))
fi

# =============================================================================
# VALIDATION DE LA SÉCURITÉ
# =============================================================================

echo ""
echo "Vérification des bonnes pratiques de sécurité..."
echo ""

# Vérifier les secrets dans les fichiers (ne devrait pas y en avoir)
echo "   → Vérification des secrets dans le code..."
secrets_found=$(grep -r "PASSWORD\|SECRET\|API_KEY\|PRIVATE_KEY" app --include="*.py" --include="*.yaml" --include="*.yml" --include="*.json" | grep -v "env\|getenv\|os.environ" | wc -l)
if [ $secrets_found -eq 0 ]; then
    echo "   ✅ Aucun secret en dur trouvé dans le code"
else
    echo "   ❌ $secrets_found occurrence(s) de mots-clés sensibles trouvés (BLOQUANT)"
    # Afficher les fichiers concernés
    grep -r "PASSWORD\|SECRET\|API_KEY\|PRIVATE_KEY" app --include="*.py" --include="*.yaml" --include="*.yml" --include="*.json" | grep -v "env\|getenv\|os.environ" | cut -d: -f1 | sort -u | sed 's/^/     /'
    errors=$((errors + secrets_found))
fi

# Vérifier les dépendances vulnérables
echo "   → Vérification des dépendances..."
if [ -f "requirements.txt" ]; then
    echo "   ⚠️ Vérification manuelle des dépendances recommandée (pip-audit)"
fi

# =============================================================================
# VALIDATION DES PERFORMANCES
# =============================================================================

echo ""
echo "Vérification des optimisations de performance..."
echo ""

# Vérifier l'utilisation du caching
echo "   → Vérification du caching..."
if grep -r "lru_cache\|@cache\|Redis" app --include="*.py" | grep -v test | grep -v ".pyc" > /dev/null 2>&1; then
    echo "   ✅ Mécanismes de caching identifiés"
else
    echo "   ⚠️ Peu ou pas de caching identifié"
fi

# Vérifier l'utilisation de l'asynchrone
echo "   → Vérification de l'async/await..."
async_found=$(grep -r "async def\|await\|asyncio" app --include="*.py" | grep -v test | grep -v ".pyc" | wc -l)
if [ $async_found -gt 0 ]; then
    echo "   ✅ Utilisation de async/await trouvée ($async_found occurrences)"
else
    echo "   ⚠️ Peu ou pas d'utilisation de async/await"
fi

# =============================================================================
# AFFICHAGE DES RÉSULTATS
# =============================================================================

echo ""
echo "=========================================="
if [ $errors -eq 0 ]; then
    echo "✅ Gate 10: VALIDÉ"
    echo "Revue finale de code terminée avec succès"
    echo "=========================================="
    echo ""
    echo "Résumé du Build 9 - Phase 5 :"
    echo "  ✅ Gate 8 : Documentation complète"
    echo "  ✅ Gate 9 : Déploiement Staging validé"
    echo "  ✅ Gate 10: Revue finale de code validée"
    echo ""
    echo "🎉 SMART_AO V7 - Build 9 est PRÊT POUR LE STAGING !"
    echo ""
    exit 0
else
    echo "❌ Gate 10: ÉCHEC"
    echo "$errors problèmes bloquants détectés"
    echo "=========================================="
    echo ""
    echo "INTERDICTION DE PRODUCTION ET DE STAGING"
    echo "Corriger tous les problèmes avant de continuer"
    echo ""
    exit 1
fi
